# Mirrasets <mirrasets.com>
VERSION="2.2.0"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=[
"GDXF6SYWIQOKOZ7BACXHBFBLQZEIH25KOTTLWQK35GO3JKRNIFHHGBPC",
"GDGEWZMIJ2K6AEYYV2L4FYN27YJP5OVZSWCJIM662D5OS7EL6T6WBGBP",
"GA4JBPWVFUT2FETDSMSGBYDGH4FROYB5SYKLVQO7WGNZHCSB63OIKRWC",
"GC7QJZNPG7FZT2C4QV7V2NJ7EGNMC4KYS2IZUSO3ZPBUNKSUMLSJZKRW",
"GAP2JFYUBSSY65FIFUN3NTUKP6MQQ52QETQEBDM25PFMQE2EEN2EEURC",
"GCV5FAHGGXBDOUKST2GLBZMIGGEJSM4LAQKBGF2Z33W3DYWFGQAR6EUR",
"GCBYVQH3RZ4JDVFMNWETE3J6U3AW6NNGTIWNVJHNQIIEGQR4K7PLUSDC",
"GCUBSJRDDDYD74MLTKL4TZVVDAJZVZFVFL52MDF6SDNBXJMWBA5RMUSD"]

[DOCUMENTATION]
ORG_NAME="Mirrasets"
ORG_DBA="Mirrasets"
ORG_URL="https://mirrasets.com"
ORG_LOGO="https://mirrasets.com/images/mirrasets_logo.png"
ORG_OFFICIAL_EMAIL="support@mirrasets.com"
ORG_TWITTER="https://twitter.com/mirrasets"
ORG_DESCRIPTION="Mirrasets mirrors real world assets on the Stellar network. We currently provide the pegged stablecoins GBPC, KRWC, and EURC, allowing users of Stellar to hold a representation of the Great British Pound, South Korean Won, and the Euro within the ecosystem. Currently, holders of GBPC, KRWC, and EURC can exchange their tokens back to USDC through the Stellar DEX."
[[PRINCIPALS]]
email="support@mirrasets.com"

[[CURRENCIES]]
code="GBPC"
issuer="GDXF6SYWIQOKOZ7BACXHBFBLQZEIH25KOTTLWQK35GO3JKRNIFHHGBPC"
status="live"
display_decimals=7
is_asset_anchored=false
anchor_asset_type="fiat"
anchor_asset="GBP"
redemption_instructions="Redeemable through the GBPC/USDC trading pair on the SDEX."
name="British Pound Mirror"
desc="GBPC is a mirror representation of the Great British Pound on the Stellar network. Using the Stellar DEX, we keep GBPC pegged to the same value as the current market rates of real world GBP & USD. GBPC allows users of Stellar to hold a representation on the Great British Pound within the ecosystem. Each token is backed by a USDC reserve, which is verifiable by viewing our issuing wallet on the network. We ensure to always have enough USDC in reserve to buy back all issued GBPC through the SDEX. A minimum spread of 1.25% is set by the issuing wallet on buy & sell offers, with offers updated regularly to reflect other market prices. Visit us at https://mirrasets.com"
image="https://mirrasets.com/images/tokens/GBPC.png"

[[CURRENCIES]]
code="KRWC"
issuer="GA4JBPWVFUT2FETDSMSGBYDGH4FROYB5SYKLVQO7WGNZHCSB63OIKRWC"
status="live"
display_decimals=7
is_asset_anchored=false
anchor_asset_type="fiat"
anchor_asset="KRW"
redemption_instructions="Redeemable through the KRWC/USDC trading pair on the SDEX."
name="Korean Won Mirror"
desc="KRWC is a mirror representation of the South Korean Won on the Stellar network. Using the Stellar DEX, we keep KRWC pegged to the same value as the current market rates of real world KRW & USD. KRWC allows users of Stellar to hold a representation on the South Korean Won within the ecosystem. Each token is backed by a USDC reserve, which is verifiable by viewing our issuing wallet on the network. We ensure to always have enough USDC in reserve to buy back all issued KRWC through the SDEX. A minimum spread of 1.25% is set by the issuing wallet on buy & sell offers, with offers updated regularly to reflect other market prices. Visit us at https://mirrasets.com"
image="https://mirrasets.com/images/tokens/KRWC.png"

[[CURRENCIES]]
code="EURC"
issuer="GAP2JFYUBSSY65FIFUN3NTUKP6MQQ52QETQEBDM25PFMQE2EEN2EEURC"
status="live"
display_decimals=7
is_asset_anchored=false
anchor_asset_type="fiat"
anchor_asset="EUR"
redemption_instructions="Redeemable through the EURC/USDC trading pair on the SDEX."
name="Euro Mirror"
desc="EURC is a mirror representation of the Euro on the Stellar network. Using the Stellar DEX, we keep EURC pegged to the same value as the current market rates of real world EUR & USD. EURC allows users of Stellar to hold a representation on the Euro within the ecosystem. Each token is backed by a USDC reserve, which is verifiable by viewing our issuing wallet on the network. We ensure to always have enough USDC in reserve to buy back all issued EURC through the SDEX. A minimum spread of 1.25% is set by the issuing wallet on buy & sell offers, with offers updated regularly to reflect other market prices. Visit us at https://mirrasets.com"
image="https://mirrasets.com/images/tokens/EURC.png"

[[CURRENCIES]]
code="USDC"
issuer="GCBYVQH3RZ4JDVFMNWETE3J6U3AW6NNGTIWNVJHNQIIEGQR4K7PLUSDC"
status="live"
display_decimals=7
is_asset_anchored=false
anchor_asset_type="fiat"
anchor_asset="USD"
redemption_instructions="Redeemable through the USDC/USDC trading pair on the SDEX."
name="US Dollar Mirror"
desc="USDC is a mirror representation of the United States Dollar on the Stellar network. Using the Stellar DEX, we keep USDC pegged to the same value as the current market rates of real world USD. USDC allows users of Stellar to hold a representation on the United States Dollar within the ecosystem. Each token is backed by a USDC reserve, which is verifiable by viewing our issuing wallet on the network. We ensure to always have enough USDC in reserve to buy back all issued USDC through the SDEX. Visit us at https://mirrasets.com"
image="https://mirrasets.com/images/tokens/USDC.png"
